version: "3"

tasks:
  default:
    deps: [main]

  main:
    aliases: [m]
    cmds:
      - bun run tauri dev

  build:
    aliases: [b]
    cmds:
      - bun run tauri build

  ver:patch:
    desc: Bump patch version (0.0.x)
    cmds: [bun scripts/bump-version.ts patch]

  ver:minor:
    desc: Bump minor version (0.x.0)
    cmds: [bun scripts/bump-version.ts minor]

  ver:major:
    desc: Bump major version (x.0.0)
    cmds: [bun scripts/bump-version.ts major]
